# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e56fb75294883f1af63db0200e9323b1a078eae1b3752230b7e0e9768c56bbbc3ee96cfe0e97b624220d65b104309da2b329691721186f7ecaa6c990b565310b

test:
  secret_key_base: e92940be4aba0aee837ee84de03385084ab297f873a9f42476bec8af57bcb6d77f12dbfa327fd9a5d07d5f832c188414c98084a2d016190b4b55c24279a84451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
